= JDBC YugaByteDB Example

Sample JDBC application using the cluster-aware https://github.com/yugabyte/jdbc-yugabytedb[YugabyteDB JDBC driver].

== Usage:

=== 1. Install YugabyteDB

See full instructions https://docs.yugabyte.com/latest/quick-start/install/[here].
For instance on macOS:

[source,sh]
----
sudo ifconfig lo0 alias 127.0.0.2
sudo ifconfig lo0 alias 127.0.0.3
sudo ifconfig lo0 alias 127.0.0.4
sudo ifconfig lo0 alias 127.0.0.5
sudo ifconfig lo0 alias 127.0.0.6
sudo ifconfig lo0 alias 127.0.0.7
wget https://downloads.yugabyte.com/yugabyte-2.7.1.1-darwin.tar.gz
tar xvfz yugabyte-2.7.1.1-darwin.tar.gz && rm && cd yugabyte-2.7.1.1/
----

=== 2. Build the demo examples
Run `mvn package` before starting the `run` script

=== 3. Run this script for a demo
Once you have YugaByteDB installed in your system, then for a demo you just need to run this script.
The script can be run in verbose and/or interactive mode. Check the help of the script to understand
the usage.

The script starts a cluster, demonstrates different flavors of load balancing through java apps.
At the end of the demo it destroys the cluster.

[source, sh]
---
./run.sh [-v] [-i] -D <path/to/yugabyte/installation/>
---
where
 -v is for VERBOSE mode
 -i is for INTERACTIVE mode
 and `<path/to/yugabyte/installation/>` is the path to the directory where yugabyte was installed in step 1.

for example: `./run.sh -v -i -D ~/yugabyte-2.7.1.1/`

This script will first show you a menu, from where you will have to select the option based on which example you want to run among UniformLoadBalance and TopologyAwareLoadBalance.
Then the corresponding script will start running with its java app in background.
